---
# tasks file for secure_ssh


- name: Create group
  ansible.builtin.group:
    name: "{{ secret_user_group }}"
    state: present

- name: Create user
  user:
    name: "{{ secret_user_name }}"
    password: "{{ secret_user_passwd }}"
    group: "{{ secret_user_group }}"
    groups: sudo
    append: yes
    create_home: yes
    shell: /bin/bash
    state: present

- name: Create .ssh
  file:
    path: /home/"{{ secret_user_name }}"/.ssh/
    state: directory
    owner: "{{ secret_user_name }}"
    group: "{{ secret_user_group }}"
    mode: 0700

- name: Create authorized_keys
  file:
    dest: /home/"{{ secret_user_name }}"/.ssh/authorized_keys
    state: touch
    owner: "{{ secret_user_name }}"
    group: "{{ secret_user_group }}"
    mode: 0600

- name: static public key
  lineinfile:
    path: /home/"{{ secret_user_name }}"/.ssh/authorized_keys
    line: "{{ user_pubkey }}"

- name: Disable PasswordAuthentication
  lineinfile:
    path: "{{ path_sshd_config }}"
    regexp: ^#PasswordAuthentication
    line: 'PasswordAuthentication no'
  notify: restart_ssh

- name: Disable PermitRootLogin
  lineinfile:
    path: "{{ path_sshd_config }}"
    regexp: ^#PermitRootLogin
    line: 'PermitRootLogin no'

- name: Disable ChallengeResponseAuthentication
  lineinfile:
    path: "{{ path_sshd_config }}"
    regexp: ^#ChallengeResponseAuthentication
    line: 'ChallengeResponseAuthentication no'

- name: Disable UsePAM
  lineinfile:
    path: "{{ path_sshd_config }}"
    regexp: ^#UsePAM
    line: 'UsePAM no'

- name: Add AuthenticationMethods publickey
  lineinfile:
    path: "{{ path_sshd_config }}"
    line: 'AuthenticationMethods publickey'

- name: Add PubkeyAuthentication
  lineinfile:
    path: "{{ path_sshd_config }}"
    line: 'PubkeyAuthentication yes'

- name: Limint users
  lineinfile:
    path: "{{ path_sshd_config }}"
    line: 'AllowUsers "{{ user_name }}"'

- name: Disable PermitEmptyPasswords
  lineinfile:
    path: "{{ path_sshd_config }}"
    regexp: ^#PermitEmptyPasswords
    line: 'PermitEmptyPasswords no'
- 
    

