---
# tasks file for create_webserver
- name: Install packages
  apt:
    name: 
      - apache2
      - php
    state: latest
    update_cache: yes

- name: Start apache2
  service:
    name: apache2
    state: started
    enabled: yes
  