# install-services.yml
---
  - hosts: lb
    become: true
    tasks: 
      - name: Install apache
        apt: name=apache2 state=latest
      - name: ensure apache starts
        service: name=apache2 state=started enabled=yes
  
  - hosts: web
    become: true
    tasks: 
      - name: Install services
        apt:
          name:
            - apache2
            - php
          state: present
      - name: Ensure apache start
        service: name=apache2 state=started enabled=yes
